### ISSUE TITLE
How to disable micrometer?

### ISSUE THREAD

**Issue by samodadela** [quarkiverse/quarkus-micrometer-registry#127]
One of my Quarkus cloud functions (CF) started to report the following error:
```
2021-10-27 14:54:40,198 ERROR [io.qua.mic.run.exp.ConfigAdapter] (main) quarkus.micrometer.export.stackdriver.project-id is required
```
That's because the classpath contains:
```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-micrometer</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.micrometer.registry</groupId>
            <artifactId>quarkus-micrometer-registry-stackdriver</artifactId>
        </dependency>
```
The micrometer dependecies come from a dependency of the CF.

At first I thought that I'd add:
```
quarkus.micrometer.export.stackdriver.project-id=myproject
```

However, as soon as I do that, I get:
```
2021-10-27 15:01:30.058:INFO:oejs.Server:main: jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: 7b38981d25d14afb4a12ff1f2596756144edf695; jvm 11+28
2021-10-27 15:01:30.099:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@66a472b9{/,null,AVAILABLE}
Exception in thread "main" java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8080
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.server.Server.doStart(Server.java:385)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:270)
        at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:127)
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:461)
        at java.base/sun.nio.ch.Net.bind(Net.java:453)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
        ... 8 more
```

Problem is that the CF tries to listen on 8080 using jetty; quarkus micrometer also starts some http server on 8080. Both obviously don't work together.

I tried to disable micrometer/stackdriver registry:
```
quarkus.micrometer.enabled=false
quarkus.micrometer.export.stackdriver.enabled=false
quarkus.micrometer.binder.http-server.enabled=false
quarkus.micrometer.registry-enabled-default=false
quarkus.micrometer.binder-enabled-default=false
```
... none of those work. I either get the error about missing project-id or CF does not start because micrometer is already using 8080.

So the question is: Is there a way to disable quarkus micrometer/stackdriver/prometheus even though they are in the classpath? 

I though `quarkus.micrometer.enabled=false` would disable everything, but it does not.

Using:
```
io.quarkus:quarkus-micrometer:jar:2.3.0.Final:compile
io.quarkiverse.micrometer.registry:quarkus-micrometer-registry-stackdriver:jar:2.2.2:compile
```

Quarkus: 2.3.0.Final

**Comment by samodadela** [comment]
@ebullient Thanks for helping. By changing the port (--port 9090) I was able to start the server, then it is also possible to disable micrometer with `quarkus.micrometer.enabled=false`. 

The other 'thing' on 8080 is Quarkus:
```
INFO: google-cloud-functions-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.4.0.Final) started in 0.733s. Listening on: http://0.0.0.0:8080
```
Didn't see that before :(

Adding micrometer+stackdriver just adds more quarkus dependencies - among which is the one that listens on 8080.
